spring:
  application:
    name: student-enrollment-api
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/student_enrollment_db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:student_user}
    password: ${DB_PASSWORD:student_password}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false

server:
  port: 8080
